### ISSUE TITLE
Make it more flexible

### ISSUE THREAD

**Issue by doubleTroub1e** [mhqb365/quack-quack-game#3]
Hey, you code looks really great, would it be possible to add some dockerfile so that it could be started on any machine? 
ex: I do have some raspberry pi3 and pi4 which I would like to use for this but getting correct version on node and making it run a bit troublesome.
having a docker image which can be easy started would solve a lot issues with dependencies and other

**Comment by mhqb365** [comment]
I thinking about that

**Comment by doubleTroub1e** [comment]
this one would work fine
```
FROM node:lts-alpine3.20

WORKDIR /app

COPY . .

RUN npm install

CMD [ "node", "quack.js", "2" ]
```

Also, some docker compose could be used to start:

```
x-defaults:
  &default-service
  restart: unless-stopped
  stop_signal: SIGINT
  tty: true
  logging:
    driver: "json-file"
    options:
      max-size: 1m


services:
  quack-quack-game:
    <<: *default-service
    image: my-docker-image:tag
    container_name: 'quack-quack-game'
    environment:
      - TOKEN="mytokenhere'
```
